### PR TITLE
Get Block module ready for Laravel 8 support

### PR DESCRIPTION
**Pull request by mikemand**
This will go with the [Laravel 8 upgrade PR on Platform](https://github.com/AsgardCms/Platform/pull/793).

### CODE REVIEW

**Comment by nWidart** [comment]
I'm getting this in travis:

```
Root composer.json requires php ^7.3 but your php version (7.2.15) does not satisfy that requirement.
```

I'm guessing the travis file needs to be adapted.

**Comment by mikemand** [comment]
Whoops, my fault. I forgot Travis. I will update the config.

Either way, tests won't work until that PR on Platform is merged (since this requires the Core module, and I can't get it to install currently because it complains about dependencies).

**Comment by mikemand** [comment]
Can you trigger Travis again, or do I need to do another commit?

**Comment by nWidart** [comment]
restarted

**Comment by nWidart** [comment]
Back to green, thanks! 👍

**Pull request merged**
